### ISSUE TITLE
Displaying time in GMT instead of local timezone on IOS device

### ISSUE THREAD

**Issue by vickyintokyo** [roggervalf/react-appointment-picker#8]
Hi There,
This component works perfectly on the Chrome, Firefox mobile emulators perfectly.
But when i check it on the real mobile device it is showing as Invalid date.
My gut feeling is it is due to you are using normal date object whereas IOS specifically needs ISO date format. Can you please look into this?

**Comment by vickyintokyo** [comment]
Apologies found out the reason for invalid date. So please ignore but then i am different issue on all browser mobile emulators it is properly taking local timezone. But when i access it on real mobile device it is converting the time specified for Initialday prop to GMT.

**Comment by roggervalf** [comment]
Hi @vickyintokyo, maybe this links could help:
https://www.digitalocean.com/community/tutorials/understanding-date-and-time-in-javascript
https://stackoverflow.com/questions/10087819/convert-date-to-another-timezone-in-javascript
setting your locale that you are expecting could help. Let me know how it works.

**Comment by vickyintokyo** [comment]
@roggervalf  Thanks for the links. I couldnt get it IOS and desktop working with the one single way of creating date object. So I think i will use the screen size to decide how to create the date object. That will solve the issue for time being. But i was looking for a single way of handling IOS and desktop.  I really appreciate your help though. Thanks much.
